# feeder
feeder: st_gcn.feeder.Feeder
test_feeder_args:
  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl


# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 400
  channel: 3
  window_size: 150
  num_person: 2
  num_point: 18
  dropout: 0
  graph: st_gcn.graph.Kinetics
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True


# test
phase: test
device: 0
test_batch_size: 32
weights: ./model/kinetics-st_gcn.pt


