# feeder
feeder: st_gcn.feeder.Feeder
feeder_augmented: st_gcn.feeder.FeederAugmented
train_feeder_args:
  data_path: ./Output_skeletons_without_missing_skeletons/xsub/train_data_joint_bones.npy
  label_path: ./Output_skeletons_without_missing_skeletons/xsub/train_label_filtered.pkl

  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  mirroring: False

test_feeder_args:
  data_path: ./Output_skeletons_without_missing_skeletons/xsub/val_data_joint_bones.npy
  label_path: ./Output_skeletons_without_missing_skeletons/xsub/val_label_filtered.pkl


# model
model: st_gcn.net.ST_GCN
training: True

model_args:
  num_class: 60
  channel: 6
  window_size: 300
  num_point: 25
  num_person: 2
  mask_learning: True
  use_data_bn: True
  attention: False
  only_attention: True
  tcn_attention: True
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: True
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  relative: False
  graph: st_gcn.graph.NTU_RGB_D
  visualization: False
  graph_args:
    labeling_mode: 'spatial'


# optim
#0: old one, 1: new one
scheduler: 1
weight_decay: 0.0001
base_lr: 0.1
step: [60,90]

# training
device: [0,1,2,3]
batch_size: 16
test_batch_size: 8
num_epoch: 120
nesterov: True



